- hosts: web
  tasks:
  - name: "copy website"
    copy:
      src: site/
      dest: /var/www/default
  - name: "replace html"
    replace:
      path: /var/www/default/index.html
      regexp: 'World'
      replace: 'from {{ inventory_hostname }}'
